package com.suncm.pojo;

// Generated 2010-2-12 22:14:29 by Hibernate Tools 3.2.4.GA

/**
 * SuncmJournal generated by hbm2java
 */
public class SuncmJournal implements java.io.Serializable {

	private String seqno;
	private String actionname;
	private String actor;
	private String actime;
	private String actdesc;

	public SuncmJournal() {
	}

	public SuncmJournal(String seqno) {
		this.seqno = seqno;
	}

	public SuncmJournal(String seqno, String actionname, String actor,
			String actime, String actdesc) {
		this.seqno = seqno;
		this.actionname = actionname;
		this.actor = actor;
		this.actime = actime;
		this.actdesc = actdesc;
	}

	public String getSeqno() {
		return this.seqno;
	}

	public void setSeqno(String seqno) {
		this.seqno = seqno;
	}

	public String getActionname() {
		return this.actionname;
	}

	public void setActionname(String actionname) {
		this.actionname = actionname;
	}

	public String getActor() {
		return this.actor;
	}

	public void setActor(String actor) {
		this.actor = actor;
	}

	public String getActime() {
		return this.actime;
	}

	public void setActime(String actime) {
		this.actime = actime;
	}

	public String getActdesc() {
		return this.actdesc;
	}

	public void setActdesc(String actdesc) {
		this.actdesc = actdesc;
	}

}
