package com.suncm.pojo;

// Generated 2010-2-12 22:14:29 by Hibernate Tools 3.2.4.GA

/**
 * SuncmConUser generated by hbm2java
 */
public class SuncmConUser implements java.io.Serializable {

	private SuncmConUserId id;
	private SuncmConInfo suncmConInfo;
	private String canvote;
	private String forext1;
	private String forext2;

	public SuncmConUser() {
	}

	public SuncmConUser(SuncmConUserId id, SuncmConInfo suncmConInfo,
			String canvote) {
		this.id = id;
		this.suncmConInfo = suncmConInfo;
		this.canvote = canvote;
	}

	public SuncmConUser(SuncmConUserId id, SuncmConInfo suncmConInfo,
			String canvote, String forext1, String forext2) {
		this.id = id;
		this.suncmConInfo = suncmConInfo;
		this.canvote = canvote;
		this.forext1 = forext1;
		this.forext2 = forext2;
	}

	public SuncmConUserId getId() {
		return this.id;
	}

	public void setId(SuncmConUserId id) {
		this.id = id;
	}

	public SuncmConInfo getSuncmConInfo() {
		return this.suncmConInfo;
	}

	public void setSuncmConInfo(SuncmConInfo suncmConInfo) {
		this.suncmConInfo = suncmConInfo;
	}

	public String getCanvote() {
		return this.canvote;
	}

	public void setCanvote(String canvote) {
		this.canvote = canvote;
	}

	public String getForext1() {
		return this.forext1;
	}

	public void setForext1(String forext1) {
		this.forext1 = forext1;
	}

	public String getForext2() {
		return this.forext2;
	}

	public void setForext2(String forext2) {
		this.forext2 = forext2;
	}

}
