package com.suncm.pojo;

// Generated 2010-2-12 22:14:29 by Hibernate Tools 3.2.4.GA

/**
 * SuncmProcatePageset generated by hbm2java
 */
public class SuncmProcatePageset implements java.io.Serializable {

	private SuncmProcatePagesetId id;
	private SuncmProjectCate suncmProjectCate;
	private String propertyName;
	private String itemdesc;
	private int pagetype;
	private int isforced;
	private int readonly;
	private Integer minlength;
	private Integer maxlength;
	private String options;
	private int ismodify;
	private int isqcon;
	private int isinlist;
	private String forext1;
	private String forext2;

	public SuncmProcatePageset() {
	}

	public SuncmProcatePageset(SuncmProcatePagesetId id,
			SuncmProjectCate suncmProjectCate, String propertyName,
			int pagetype, int isforced, int readonly, int ismodify, int isqcon,
			int isinlist) {
		this.id = id;
		this.suncmProjectCate = suncmProjectCate;
		this.propertyName = propertyName;
		this.pagetype = pagetype;
		this.isforced = isforced;
		this.readonly = readonly;
		this.ismodify = ismodify;
		this.isqcon = isqcon;
		this.isinlist = isinlist;
	}

	public SuncmProcatePageset(SuncmProcatePagesetId id,
			SuncmProjectCate suncmProjectCate, String propertyName,
			String itemdesc, int pagetype, int isforced, int readonly,
			Integer minlength, Integer maxlength, String options, int ismodify,
			int isqcon, int isinlist, String forext1, String forext2) {
		this.id = id;
		this.suncmProjectCate = suncmProjectCate;
		this.propertyName = propertyName;
		this.itemdesc = itemdesc;
		this.pagetype = pagetype;
		this.isforced = isforced;
		this.readonly = readonly;
		this.minlength = minlength;
		this.maxlength = maxlength;
		this.options = options;
		this.ismodify = ismodify;
		this.isqcon = isqcon;
		this.isinlist = isinlist;
		this.forext1 = forext1;
		this.forext2 = forext2;
	}

	public SuncmProcatePagesetId getId() {
		return this.id;
	}

	public void setId(SuncmProcatePagesetId id) {
		this.id = id;
	}

	public SuncmProjectCate getSuncmProjectCate() {
		return this.suncmProjectCate;
	}

	public void setSuncmProjectCate(SuncmProjectCate suncmProjectCate) {
		this.suncmProjectCate = suncmProjectCate;
	}

	public String getPropertyName() {
		return this.propertyName;
	}

	public void setPropertyName(String propertyName) {
		this.propertyName = propertyName;
	}

	public String getItemdesc() {
		return this.itemdesc;
	}

	public void setItemdesc(String itemdesc) {
		this.itemdesc = itemdesc;
	}

	public int getPagetype() {
		return this.pagetype;
	}

	public void setPagetype(int pagetype) {
		this.pagetype = pagetype;
	}

	public int getIsforced() {
		return this.isforced;
	}

	public void setIsforced(int isforced) {
		this.isforced = isforced;
	}

	public int getReadonly() {
		return this.readonly;
	}

	public void setReadonly(int readonly) {
		this.readonly = readonly;
	}

	public Integer getMinlength() {
		return this.minlength;
	}

	public void setMinlength(Integer minlength) {
		this.minlength = minlength;
	}

	public Integer getMaxlength() {
		return this.maxlength;
	}

	public void setMaxlength(Integer maxlength) {
		this.maxlength = maxlength;
	}

	public String getOptions() {
		return this.options;
	}

	public void setOptions(String options) {
		this.options = options;
	}

	public int getIsmodify() {
		return this.ismodify;
	}

	public void setIsmodify(int ismodify) {
		this.ismodify = ismodify;
	}

	public int getIsqcon() {
		return this.isqcon;
	}

	public void setIsqcon(int isqcon) {
		this.isqcon = isqcon;
	}

	public int getIsinlist() {
		return this.isinlist;
	}

	public void setIsinlist(int isinlist) {
		this.isinlist = isinlist;
	}

	public String getForext1() {
		return this.forext1;
	}

	public void setForext1(String forext1) {
		this.forext1 = forext1;
	}

	public String getForext2() {
		return this.forext2;
	}

	public void setForext2(String forext2) {
		this.forext2 = forext2;
	}

}
