package com.suncm.pojo;

// Generated 2010-2-12 22:14:29 by Hibernate Tools 3.2.4.GA

import java.util.HashSet;
import java.util.Set;

/**
 * SuncmConInfo generated by hbm2java
 */
public class SuncmConInfo implements java.io.Serializable {

	private String conId;
	private SuncmConCate suncmConCate;
	private String conNo;
	private String conName;
	private String directer;
	private String confduetime;
	private String confaddr;
	private String conftitle;
	private String confcreatetime;
	private String confcreator;
	private String confsum;
	private String confnow;
	private String forext1;
	private String forext2;
	private Set<SuncmConProject> suncmConProjects = new HashSet<SuncmConProject>(
			0);
	private Set<SuncmConUser> suncmConUsers = new HashSet<SuncmConUser>(0);

	public SuncmConInfo() {
	}

	public SuncmConInfo(String conId, SuncmConCate suncmConCate, String conNo,
			String conName, String confnow) {
		this.conId = conId;
		this.suncmConCate = suncmConCate;
		this.conNo = conNo;
		this.conName = conName;
		this.confnow = confnow;
	}

	public SuncmConInfo(String conId, SuncmConCate suncmConCate, String conNo,
			String conName, String directer, String confduetime,
			String confaddr, String conftitle, String confcreatetime,
			String confcreator, String confsum, String confnow, String forext1,
			String forext2, Set<SuncmConProject> suncmConProjects,
			Set<SuncmConUser> suncmConUsers) {
		this.conId = conId;
		this.suncmConCate = suncmConCate;
		this.conNo = conNo;
		this.conName = conName;
		this.directer = directer;
		this.confduetime = confduetime;
		this.confaddr = confaddr;
		this.conftitle = conftitle;
		this.confcreatetime = confcreatetime;
		this.confcreator = confcreator;
		this.confsum = confsum;
		this.confnow = confnow;
		this.forext1 = forext1;
		this.forext2 = forext2;
		this.suncmConProjects = suncmConProjects;
		this.suncmConUsers = suncmConUsers;
	}

	public String getConId() {
		return this.conId;
	}

	public void setConId(String conId) {
		this.conId = conId;
	}

	public SuncmConCate getSuncmConCate() {
		return this.suncmConCate;
	}

	public void setSuncmConCate(SuncmConCate suncmConCate) {
		this.suncmConCate = suncmConCate;
	}

	public String getConNo() {
		return this.conNo;
	}

	public void setConNo(String conNo) {
		this.conNo = conNo;
	}

	public String getConName() {
		return this.conName;
	}

	public void setConName(String conName) {
		this.conName = conName;
	}

	public String getDirecter() {
		return this.directer;
	}

	public void setDirecter(String directer) {
		this.directer = directer;
	}

	public String getConfduetime() {
		return this.confduetime;
	}

	public void setConfduetime(String confduetime) {
		this.confduetime = confduetime;
	}

	public String getConfaddr() {
		return this.confaddr;
	}

	public void setConfaddr(String confaddr) {
		this.confaddr = confaddr;
	}

	public String getConftitle() {
		return this.conftitle;
	}

	public void setConftitle(String conftitle) {
		this.conftitle = conftitle;
	}

	public String getConfcreatetime() {
		return this.confcreatetime;
	}

	public void setConfcreatetime(String confcreatetime) {
		this.confcreatetime = confcreatetime;
	}

	public String getConfcreator() {
		return this.confcreator;
	}

	public void setConfcreator(String confcreator) {
		this.confcreator = confcreator;
	}

	public String getConfsum() {
		return this.confsum;
	}

	public void setConfsum(String confsum) {
		this.confsum = confsum;
	}

	public String getConfnow() {
		return this.confnow;
	}

	public void setConfnow(String confnow) {
		this.confnow = confnow;
	}

	public String getForext1() {
		return this.forext1;
	}

	public void setForext1(String forext1) {
		this.forext1 = forext1;
	}

	public String getForext2() {
		return this.forext2;
	}

	public void setForext2(String forext2) {
		this.forext2 = forext2;
	}

	public Set<SuncmConProject> getSuncmConProjects() {
		return this.suncmConProjects;
	}

	public void setSuncmConProjects(Set<SuncmConProject> suncmConProjects) {
		this.suncmConProjects = suncmConProjects;
	}

	public Set<SuncmConUser> getSuncmConUsers() {
		return this.suncmConUsers;
	}

	public void setSuncmConUsers(Set<SuncmConUser> suncmConUsers) {
		this.suncmConUsers = suncmConUsers;
	}

}
