package com.suncm.pojo;

// Generated 2010-2-12 22:14:29 by Hibernate Tools 3.2.4.GA

/**
 * SuncmProjectExt generated by hbm2java
 */
public class SuncmProjectExt implements java.io.Serializable {

	private SuncmProjectExtId id;
	private SuncmProjectInfo suncmProjectInfo;
	private String propertyName;
	private String propertyValue;

	public SuncmProjectExt() {
	}

	public SuncmProjectExt(SuncmProjectExtId id,
			SuncmProjectInfo suncmProjectInfo, String propertyName) {
		this.id = id;
		this.suncmProjectInfo = suncmProjectInfo;
		this.propertyName = propertyName;
	}

	public SuncmProjectExt(SuncmProjectExtId id,
			SuncmProjectInfo suncmProjectInfo, String propertyName,
			String propertyValue) {
		this.id = id;
		this.suncmProjectInfo = suncmProjectInfo;
		this.propertyName = propertyName;
		this.propertyValue = propertyValue;
	}

	public SuncmProjectExtId getId() {
		return this.id;
	}

	public void setId(SuncmProjectExtId id) {
		this.id = id;
	}

	public SuncmProjectInfo getSuncmProjectInfo() {
		return this.suncmProjectInfo;
	}

	public void setSuncmProjectInfo(SuncmProjectInfo suncmProjectInfo) {
		this.suncmProjectInfo = suncmProjectInfo;
	}

	public String getPropertyName() {
		return this.propertyName;
	}

	public void setPropertyName(String propertyName) {
		this.propertyName = propertyName;
	}

	public String getPropertyValue() {
		return this.propertyValue;
	}

	public void setPropertyValue(String propertyValue) {
		this.propertyValue = propertyValue;
	}

}
