package com.suncm.pojo;

// Generated 2010-2-12 22:14:29 by Hibernate Tools 3.2.4.GA

import java.util.HashSet;
import java.util.Set;

/**
 * SuncmConCate generated by hbm2java
 */
public class SuncmConCate implements java.io.Serializable {

	private String conCategoryId;
	private SuncmVoteMethods suncmVoteMethods;
	private String conCategoryName;
	private String isqueue;
	private String isagridea;
	private String isdpridea;
	private String isrejidea;
	private String leastmem;
	private String memreftime;
	private String decidereftime;
	private String forext1;
	private String forext2;
	private Set<SuncmConInfo> suncmConInfos = new HashSet<SuncmConInfo>(0);

	public SuncmConCate() {
	}

	public SuncmConCate(String conCategoryId,
			SuncmVoteMethods suncmVoteMethods, String conCategoryName) {
		this.conCategoryId = conCategoryId;
		this.suncmVoteMethods = suncmVoteMethods;
		this.conCategoryName = conCategoryName;
	}

	public SuncmConCate(String conCategoryId,
			SuncmVoteMethods suncmVoteMethods, String conCategoryName,
			String isqueue, String isagridea, String isdpridea,
			String isrejidea, String leastmem, String memreftime,
			String decidereftime, String forext1, String forext2,
			Set<SuncmConInfo> suncmConInfos) {
		this.conCategoryId = conCategoryId;
		this.suncmVoteMethods = suncmVoteMethods;
		this.conCategoryName = conCategoryName;
		this.isqueue = isqueue;
		this.isagridea = isagridea;
		this.isdpridea = isdpridea;
		this.isrejidea = isrejidea;
		this.leastmem = leastmem;
		this.memreftime = memreftime;
		this.decidereftime = decidereftime;
		this.forext1 = forext1;
		this.forext2 = forext2;
		this.suncmConInfos = suncmConInfos;
	}

	public String getConCategoryId() {
		return this.conCategoryId;
	}

	public void setConCategoryId(String conCategoryId) {
		this.conCategoryId = conCategoryId;
	}

	public SuncmVoteMethods getSuncmVoteMethods() {
		return this.suncmVoteMethods;
	}

	public void setSuncmVoteMethods(SuncmVoteMethods suncmVoteMethods) {
		this.suncmVoteMethods = suncmVoteMethods;
	}

	public String getConCategoryName() {
		return this.conCategoryName;
	}

	public void setConCategoryName(String conCategoryName) {
		this.conCategoryName = conCategoryName;
	}

	public String getIsqueue() {
		return this.isqueue;
	}

	public void setIsqueue(String isqueue) {
		this.isqueue = isqueue;
	}

	public String getIsagridea() {
		return this.isagridea;
	}

	public void setIsagridea(String isagridea) {
		this.isagridea = isagridea;
	}

	public String getIsdpridea() {
		return this.isdpridea;
	}

	public void setIsdpridea(String isdpridea) {
		this.isdpridea = isdpridea;
	}

	public String getIsrejidea() {
		return this.isrejidea;
	}

	public void setIsrejidea(String isrejidea) {
		this.isrejidea = isrejidea;
	}

	public String getLeastmem() {
		return this.leastmem;
	}

	public void setLeastmem(String leastmem) {
		this.leastmem = leastmem;
	}

	public String getMemreftime() {
		return this.memreftime;
	}

	public void setMemreftime(String memreftime) {
		this.memreftime = memreftime;
	}

	public String getDecidereftime() {
		return this.decidereftime;
	}

	public void setDecidereftime(String decidereftime) {
		this.decidereftime = decidereftime;
	}

	public String getForext1() {
		return this.forext1;
	}

	public void setForext1(String forext1) {
		this.forext1 = forext1;
	}

	public String getForext2() {
		return this.forext2;
	}

	public void setForext2(String forext2) {
		this.forext2 = forext2;
	}

	public Set<SuncmConInfo> getSuncmConInfos() {
		return this.suncmConInfos;
	}

	public void setSuncmConInfos(Set<SuncmConInfo> suncmConInfos) {
		this.suncmConInfos = suncmConInfos;
	}

}
