package com.suncm.pojo;

// Generated 2010-2-12 22:14:29 by Hibernate Tools 3.2.4.GA

import java.util.HashSet;
import java.util.Set;

/**
 * SuncmVoteMethods generated by hbm2java
 */
public class SuncmVoteMethods implements java.io.Serializable {

	private String vmid;
	private String vmname;
	private String isrdname;
	private String vipreject;
	private String remark;
	private String formula;
	private String forext1;
	private String forext2;
	private Set<SuncmConCate> suncmConCates = new HashSet<SuncmConCate>(0);

	public SuncmVoteMethods() {
	}

	public SuncmVoteMethods(String vmid, String vmname) {
		this.vmid = vmid;
		this.vmname = vmname;
	}

	public SuncmVoteMethods(String vmid, String vmname, String isrdname,
			String vipreject, String remark, String formula, String forext1,
			String forext2, Set<SuncmConCate> suncmConCates) {
		this.vmid = vmid;
		this.vmname = vmname;
		this.isrdname = isrdname;
		this.vipreject = vipreject;
		this.remark = remark;
		this.formula = formula;
		this.forext1 = forext1;
		this.forext2 = forext2;
		this.suncmConCates = suncmConCates;
	}

	public String getVmid() {
		return this.vmid;
	}

	public void setVmid(String vmid) {
		this.vmid = vmid;
	}

	public String getVmname() {
		return this.vmname;
	}

	public void setVmname(String vmname) {
		this.vmname = vmname;
	}

	public String getIsrdname() {
		return this.isrdname;
	}

	public void setIsrdname(String isrdname) {
		this.isrdname = isrdname;
	}

	public String getVipreject() {
		return this.vipreject;
	}

	public void setVipreject(String vipreject) {
		this.vipreject = vipreject;
	}

	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	public String getFormula() {
		return this.formula;
	}

	public void setFormula(String formula) {
		this.formula = formula;
	}

	public String getForext1() {
		return this.forext1;
	}

	public void setForext1(String forext1) {
		this.forext1 = forext1;
	}

	public String getForext2() {
		return this.forext2;
	}

	public void setForext2(String forext2) {
		this.forext2 = forext2;
	}

	public Set<SuncmConCate> getSuncmConCates() {
		return this.suncmConCates;
	}

	public void setSuncmConCates(Set<SuncmConCate> suncmConCates) {
		this.suncmConCates = suncmConCates;
	}

}
