package com.suncm.pojo;

// Generated 2010-2-12 22:14:29 by Hibernate Tools 3.2.4.GA

import java.math.BigDecimal;

/**
 * SuncmErrorJournal generated by hbm2java
 */
public class SuncmErrorJournal implements java.io.Serializable {

	private String seqno;
	private String actionname;
	private String actor;
	private String actime;
	private String actdesc;
	private String errorcode;
	private String errordesc;
	private String errorlocation;

	public SuncmErrorJournal() {
	}

	public SuncmErrorJournal(String seqno) {
		this.seqno = seqno;
	}

	public SuncmErrorJournal(String seqno, String actionname, String actor,
			String actime, String actdesc, String errorcode, String errordesc,
			String errorlocation) {
		this.seqno = seqno;
		this.actionname = actionname;
		this.actor = actor;
		this.actime = actime;
		this.actdesc = actdesc;
		this.errorcode = errorcode;
		this.errordesc = errordesc;
		this.errorlocation = errorlocation;
	}

	public String getSeqno() {
		return this.seqno;
	}

	public void setSeqno(String seqno) {
		this.seqno = seqno;
	}

	public String getActionname() {
		return this.actionname;
	}

	public void setActionname(String actionname) {
		this.actionname = actionname;
	}

	public String getActor() {
		return this.actor;
	}

	public void setActor(String actor) {
		this.actor = actor;
	}

	public String getActime() {
		return this.actime;
	}

	public void setActime(String actime) {
		this.actime = actime;
	}

	public String getActdesc() {
		return this.actdesc;
	}

	public void setActdesc(String actdesc) {
		this.actdesc = actdesc;
	}

	public String getErrorcode() {
		return this.errorcode;
	}

	public void setErrorcode(String errorcode) {
		this.errorcode = errorcode;
	}

	public String getErrordesc() {
		return this.errordesc;
	}

	public void setErrordesc(String errordesc) {
		this.errordesc = errordesc;
	}

	public String getErrorlocation() {
		return this.errorlocation;
	}

	public void setErrorlocation(String errorlocation) {
		this.errorlocation = errorlocation;
	}

}
