package com.suncm.pojo;

// Generated 2010-2-12 22:14:29 by Hibernate Tools 3.2.4.GA

import java.util.HashSet;
import java.util.Set;

/**
 * SuncmProjectCate generated by hbm2java
 */
public class SuncmProjectCate implements java.io.Serializable {

	private String projectCateId;
	private String projectCateName;
	private String wflid;
	private String wflname;
	private int projectCateStat;
	private String forext1;
	private String forext2;
	private Set<SuncmProjectInfo> suncmProjectInfos = new HashSet<SuncmProjectInfo>(
			0);
	private Set<SuncmProcatePageset> suncmProcatePagesets = new HashSet<SuncmProcatePageset>(
			0);

	public SuncmProjectCate() {
	}

	public SuncmProjectCate(String projectCateId, String projectCateName,
			int projectCateStat) {
		this.projectCateId = projectCateId;
		this.projectCateName = projectCateName;
		this.projectCateStat = projectCateStat;
	}

	public SuncmProjectCate(String projectCateId, String projectCateName,
			String wflid, String wflname, int projectCateStat, String forext1,
			String forext2, Set<SuncmProjectInfo> suncmProjectInfos,
			Set<SuncmProcatePageset> suncmProcatePagesets) {
		this.projectCateId = projectCateId;
		this.projectCateName = projectCateName;
		this.wflid = wflid;
		this.wflname = wflname;
		this.projectCateStat = projectCateStat;
		this.forext1 = forext1;
		this.forext2 = forext2;
		this.suncmProjectInfos = suncmProjectInfos;
		this.suncmProcatePagesets = suncmProcatePagesets;
	}

	public String getProjectCateId() {
		return this.projectCateId;
	}

	public void setProjectCateId(String projectCateId) {
		this.projectCateId = projectCateId;
	}

	public String getProjectCateName() {
		return this.projectCateName;
	}

	public void setProjectCateName(String projectCateName) {
		this.projectCateName = projectCateName;
	}

	public String getWflid() {
		return this.wflid;
	}

	public void setWflid(String wflid) {
		this.wflid = wflid;
	}

	public String getWflname() {
		return this.wflname;
	}

	public void setWflname(String wflname) {
		this.wflname = wflname;
	}

	public int getProjectCateStat() {
		return this.projectCateStat;
	}

	public void setProjectCateStat(int projectCateStat) {
		this.projectCateStat = projectCateStat;
	}

	public String getForext1() {
		return this.forext1;
	}

	public void setForext1(String forext1) {
		this.forext1 = forext1;
	}

	public String getForext2() {
		return this.forext2;
	}

	public void setForext2(String forext2) {
		this.forext2 = forext2;
	}

	public Set<SuncmProjectInfo> getSuncmProjectInfos() {
		return this.suncmProjectInfos;
	}

	public void setSuncmProjectInfos(Set<SuncmProjectInfo> suncmProjectInfos) {
		this.suncmProjectInfos = suncmProjectInfos;
	}

	public Set<SuncmProcatePageset> getSuncmProcatePagesets() {
		return this.suncmProcatePagesets;
	}

	public void setSuncmProcatePagesets(
			Set<SuncmProcatePageset> suncmProcatePagesets) {
		this.suncmProcatePagesets = suncmProcatePagesets;
	}

}
