package com.suncm.pojo;

// Generated 2010-2-12 22:14:29 by Hibernate Tools 3.2.4.GA

/**
 * SuncmSystemParam generated by hbm2java
 */
public class SuncmSystemParam implements java.io.Serializable {

	private String paramname;
	private String paramvalue;
	private String modifier;
	private String modifytime;

	public SuncmSystemParam() {
	}

	public SuncmSystemParam(String paramname) {
		this.paramname = paramname;
	}

	public SuncmSystemParam(String paramname, String paramvalue,
			String modifier, String modifytime) {
		this.paramname = paramname;
		this.paramvalue = paramvalue;
		this.modifier = modifier;
		this.modifytime = modifytime;
	}

	public String getParamname() {
		return this.paramname;
	}

	public void setParamname(String paramname) {
		this.paramname = paramname;
	}

	public String getParamvalue() {
		return this.paramvalue;
	}

	public void setParamvalue(String paramvalue) {
		this.paramvalue = paramvalue;
	}

	public String getModifier() {
		return this.modifier;
	}

	public void setModifier(String modifier) {
		this.modifier = modifier;
	}

	public String getModifytime() {
		return this.modifytime;
	}

	public void setModifytime(String modifytime) {
		this.modifytime = modifytime;
	}

}
