package com.suncm.pojo;

// Generated 2010-2-12 22:14:29 by Hibernate Tools 3.2.4.GA

/**
 * SuncmMyGroup generated by hbm2java
 */
public class SuncmMyGroup implements java.io.Serializable {

	private String groupId;
	private String groupName;
	private String userId;

	public SuncmMyGroup() {
	}

	public SuncmMyGroup(String groupId, String groupName) {
		this.groupId = groupId;
		this.groupName = groupName;
	}

	public SuncmMyGroup(String groupId, String groupName, String userId) {
		this.groupId = groupId;
		this.groupName = groupName;
		this.userId = userId;
	}

	public String getGroupId() {
		return this.groupId;
	}

	public void setGroupId(String groupId) {
		this.groupId = groupId;
	}

	public String getGroupName() {
		return this.groupName;
	}

	public void setGroupName(String groupName) {
		this.groupName = groupName;
	}

	public String getUserId() {
		return this.userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

}
